import Head from 'next/head';
import Footer from '~/components/Footer';
import Header from '~/components/Header';
import Banner from '~/components/home/Banner';
import LatestInsights from '../components/home/LatestInsights';
import LatestJobs from '../components/home/LatestJobs';
import OurSectors from '../components/home/OurSectors';
import Partners from '../components/home/Partners';
import WhatWeDo from '../components/home/WhatWeDo';
import WhyUs from '../components/home/WhyUs';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
      <Partners />
      <LatestJobs />
      <OurSectors />
      <WhyUs />
      <WhatWeDo />
      <LatestInsights />
      <Footer />
    </>
  );
}
